# Generated by Django 3.1.7 on 2023-12-06 13:41

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geovisor', '0002_marcadores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marcadores',
            name='geom',
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326),
        ),
    ]
