# Generated by Django 3.1.7 on 2023-12-07 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geovisor', '0004_auto_20231207_0439'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marcadores',
            name='descripcion',
        ),
        migrations.AddField(
            model_name='marcadores',
            name='direccion',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='marcadores',
            name='total_estudiantes',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='marcadores',
            name='nombre',
            field=models.TextField(),
        ),
    ]
